// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzFs-BnoTOPgKX33F4DIRjKnwsAJMiLYk',
    appId: '1:246734553215:web:e58215c0389b4d10c9bf4a',
    messagingSenderId: '246734553215',
    projectId: 'project-ce9a5',
    authDomain: 'project-ce9a5.firebaseapp.com',
    storageBucket: 'project-ce9a5.firebasestorage.app',
    measurementId: 'G-YQTY057QQF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDldKlSc8M44ZvLXveWoP8HDIqlN5ktwzI',
    appId: '1:246734553215:android:655ce7a78df42b76c9bf4a',
    messagingSenderId: '246734553215',
    projectId: 'project-ce9a5',
    storageBucket: 'project-ce9a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHSve9FXo6s4Bv6gcsjoysRpyYBDG_5Wk',
    appId: '1:246734553215:ios:c9860c0e61cbc3b1c9bf4a',
    messagingSenderId: '246734553215',
    projectId: 'project-ce9a5',
    storageBucket: 'project-ce9a5.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHSve9FXo6s4Bv6gcsjoysRpyYBDG_5Wk',
    appId: '1:246734553215:ios:c9860c0e61cbc3b1c9bf4a',
    messagingSenderId: '246734553215',
    projectId: 'project-ce9a5',
    storageBucket: 'project-ce9a5.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzFs-BnoTOPgKX33F4DIRjKnwsAJMiLYk',
    appId: '1:246734553215:web:e947d41fcba6cca3c9bf4a',
    messagingSenderId: '246734553215',
    projectId: 'project-ce9a5',
    authDomain: 'project-ce9a5.firebaseapp.com',
    storageBucket: 'project-ce9a5.firebasestorage.app',
    measurementId: 'G-2HTR6YXZYZ',
  );
}
